// src/docs/index.ts
// Central documentation content for self-documenting scaffolding

export const CLAUDE_MD_CONTENT = `# schema-flow — YAML Format Reference

## Directory Structure

\`\`\`
schema/
  tables/       One YAML file per table
  enums/        One YAML file per enum type
  functions/    One YAML file per function
  views/        One YAML file per view (prefix materialized views with mv_)
  roles/        One YAML file per role
  mixins/       Reusable column/index/trigger/policy sets (applied via \`use:\`)
  pre/          SQL scripts that run BEFORE declarative migration (renames, backfills)
  post/         SQL scripts that run AFTER declarative migration (seeds, grants, refreshes)
  repeatable/   SQL scripts re-applied whenever their content changes
  extensions.yaml  PostgreSQL extensions to enable
\`\`\`

## Table YAML (\`tables/<table>.yaml\`)

\`\`\`yaml
table: users
comment: "Application users"      # optional — stored as PostgreSQL COMMENT

use: [timestamps, soft_delete]     # optional — applies mixins in order

columns:
  - name: id
    type: uuid
    primary_key: true
    default: gen_random_uuid()

  - name: email
    type: text
    unique: true

  - name: role
    type: user_role               # enum type defined in enum_user_role.yaml

  - name: org_id
    type: uuid
    references:
      table: organizations
      column: id
      on_delete: CASCADE          # optional — NO ACTION if omitted
      on_update: CASCADE          # optional

  - name: score
    type: integer
    nullable: true                # columns are NOT NULL by default
    default: 0
    comment: "User score"

# Composite primary key (instead of per-column primary_key)
# primary_key: [org_id, user_id]

indexes:
  - name: idx_users_email
    columns: [email]
    unique: true
  - name: idx_users_org
    columns: [org_id]
    where: "deleted_at IS NULL"   # partial index
  # method: btree | hash | gin | gist | brin  (default: btree)
  # include: [col]  — covering index columns
  # opclass: jsonb_path_ops — index operator class

checks:
  - name: chk_users_email_format
    expression: "email ~* '^.+@.+$'"

triggers:
  - name: audit_users_changes
    timing: AFTER                 # BEFORE | AFTER | INSTEAD OF
    events: [INSERT, UPDATE]
    function: audit_log
    for_each: ROW                 # ROW | STATEMENT
    when: "OLD.* IS DISTINCT FROM NEW.*"   # optional

# Row-Level Security
rls: true
force_rls: true                   # applies even to table owner
policies:
  - name: users_tenant_isolation
    for: ALL                      # SELECT | INSERT | UPDATE | DELETE | ALL
    to: [app_user]                # optional — roles
    permissive: false             # optional — default true
    using: "tenant_id = current_setting('app.tenant_id')::uuid"
    check: "tenant_id = current_setting('app.tenant_id')::uuid"
\`\`\`

## Mixin YAML (\`mixins/<name>.yaml\`)

Mixins are reusable sets of columns, indexes, triggers, checks, and RLS policies.
Tables include them with \`use: [mixin_name]\`. Mixin columns are prepended;
table columns with the same name override the mixin version.

Use \`{table}\` in name fields — it is replaced with the consuming table's name.

\`\`\`yaml
mixin: timestamps

columns:
  - name: created_at
    type: timestamptz
    default: now()

  - name: updated_at
    type: timestamptz
    default: now()

triggers:
  - name: set_{table}_updated_at
    timing: BEFORE
    events: [UPDATE]
    function: update_timestamp
    for_each: ROW
    when: "OLD.* IS DISTINCT FROM NEW.*"
\`\`\`

## Function YAML (\`functions/<name>.yaml\`)

\`\`\`yaml
name: update_timestamp
language: plpgsql
returns: trigger
replace: true
# security: definer          # optional — runs as function owner
# args: "p_id uuid, p_name text"
body: |
  BEGIN
    NEW.updated_at = now();
    RETURN NEW;
  END;
\`\`\`

## Enum YAML (\`enums/<name>.yaml\`)

\`\`\`yaml
enum: user_role
values: [admin, editor, viewer]
comment: "User permission roles"
\`\`\`

## View YAML (\`views/<name>.yaml\`)

\`\`\`yaml
view: active_users
comment: "Non-deleted users"
query: |
  SELECT id, email, role
  FROM users
  WHERE deleted_at IS NULL
\`\`\`

## Materialized View (\`views/mv_<name>.yaml\`)

\`\`\`yaml
materialized_view: user_stats
query: |
  SELECT org_id, count(*) as user_count
  FROM users GROUP BY org_id
indexes:
  - name: idx_user_stats_org
    columns: [org_id]
    unique: true
\`\`\`

## Extensions (\`extensions.yaml\`)

\`\`\`yaml
extensions:
  - pgcrypto
  - pg_trgm
\`\`\`

## Pre/Post Scripts

Pre-migration scripts (\`pre/*.sql\`) run before declarative schema changes.
Use them for column renames, data transformations, and backfills.
Post-migration scripts (\`post/*.sql\`) run after. Use them for seed data, grants, and refreshes.
Files are sorted by name — prefix with a UTC timestamp (auto-generated by \`schema-flow new pre|post <name>\`).

## Key CLI Commands

\`\`\`
schema-flow init                    Create directory structure + docs
schema-flow generate --db <url>     Import existing DB into YAML
schema-flow plan --db <url>         Preview migration (dry run)
schema-flow run --db <url>          Apply pre → migrate → post
schema-flow validate --db <url>     Validate YAML against live DB
schema-flow drift --db <url>        Detect drift between YAML and DB
schema-flow lint --db <url>         Static analysis for dangerous patterns
schema-flow new pre <name>          Scaffold a pre-migration script
schema-flow new post <name>         Scaffold a post-migration script
schema-flow new mixin <name>        Scaffold a new mixin YAML file
schema-flow docs                    Print this reference
schema-flow erd                     Generate Mermaid ER diagram
schema-flow sql --db <url>          Export migration as SQL file
\`\`\`
`;

export const EXAMPLE_MIXIN_CONTENT = `# _example.yaml.sample — Example mixin for schema-flow
# Copy this file, remove the .sample extension, and rename to your mixin name.
# Tables include mixins with:  use: [your_mixin_name]
#
# The {table} placeholder is replaced with the consuming table's name.

# mixin: my_mixin
#
# columns:
#   - name: created_at
#     type: timestamptz
#     default: now()
#
#   - name: updated_at
#     type: timestamptz
#     default: now()
#
# indexes:
#   - name: idx_{table}_created
#     columns: [created_at]
#
# triggers:
#   - name: set_{table}_updated_at
#     timing: BEFORE
#     events: [UPDATE]
#     function: update_timestamp
#     for_each: ROW
#     when: "OLD.* IS DISTINCT FROM NEW.*"
#
# # Row-Level Security (uncomment to enable)
# # rls: true
# # force_rls: true
# # policies:
# #   - name: "{table}_tenant_isolation"
# #     for: ALL
# #     using: "tenant_id = current_setting('app.tenant_id')::uuid"
# #     check: "tenant_id = current_setting('app.tenant_id')::uuid"
`;

export function getMixinTemplate(name: string): string {
  return `# Mixin: ${name}
# Usage: add \`use: [${name}]\` to any table YAML.
# The {table} placeholder is replaced with the consuming table's name.

mixin: ${name}

# columns:
#   - name: example_col
#     type: text
#     nullable: true
#
# indexes:
#   - name: idx_{table}_example
#     columns: [example_col]
#
# triggers:
#   - name: trg_{table}_example
#     timing: BEFORE
#     events: [INSERT, UPDATE]
#     function: my_function
#     for_each: ROW
#
# checks:
#   - name: chk_{table}_example
#     expression: "example_col IS NOT NULL"
#
# rls: true
# force_rls: true
# policies:
#   - name: "{table}_example_policy"
#     for: ALL
#     using: "true"
#     check: "true"
`;
}

export function printDocsReference(): void {
  process.stdout.write(CLAUDE_MD_CONTENT);
}
