// src/scaffold/index.ts
// Scaffolding helpers: generate pre/post scripts, generate YAML from existing DB

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import { stringify as toYaml } from "yaml";
import type { SchemaFlowConfig } from "../core/config.js";
import type { TableSchema } from "../schema/types.js";
import { getExistingTables, introspectTable, getExistingFunctions } from "../introspect/index.js";
import { withClient } from "../core/db.js";
import { logger } from "../core/logger.js";

/** Generate a UTC timestamp string for filenames: YYYYMMDDHHMMSS */
function utcTimestamp(): string {
  const now = new Date();
  return now
    .toISOString()
    .replace(/[-:T]/g, "")
    .replace(/\.\d+Z/, "")
    .slice(0, 14);
}

/** Scaffold a pre-migration SQL script */
export function scaffoldPre(config: SchemaFlowConfig, name: string): string {
  const ts = utcTimestamp();
  const filename = `${ts}_${sanitizeName(name)}.sql`;
  const filePath = path.join(config.preDir, filename);

  ensureDir(config.preDir);

  const content = `-- Pre-migration script: ${name}
-- Generated by schema-flow at ${new Date().toISOString()}
-- This script runs BEFORE declarative schema migration.
-- Use for: column renames, data transformations, backfills, etc.

-- Example: rename a column
-- ALTER TABLE "public"."users" RENAME COLUMN "name" TO "full_name";

BEGIN;

-- Your SQL here

COMMIT;
`;

  writeFileSync(filePath, content, "utf-8");
  logger.success(`Created pre-migration script: ${filePath}`);
  return filePath;
}

/** Scaffold a post-migration SQL script */
export function scaffoldPost(config: SchemaFlowConfig, name: string): string {
  const ts = utcTimestamp();
  const filename = `${ts}_${sanitizeName(name)}.sql`;
  const filePath = path.join(config.postDir, filename);

  ensureDir(config.postDir);

  const content = `-- Post-migration script: ${name}
-- Generated by schema-flow at ${new Date().toISOString()}
-- This script runs AFTER declarative schema migration.
-- Use for: seed data, grants, materialized view refreshes, etc.

BEGIN;

-- Your SQL here

COMMIT;
`;

  writeFileSync(filePath, content, "utf-8");
  logger.success(`Created post-migration script: ${filePath}`);
  return filePath;
}

/** Generate YAML schema files from an existing database */
export async function generateFromDb(config: SchemaFlowConfig): Promise<string[]> {
  logger.banner("Generating schema files from existing database");
  const generatedFiles: string[] = [];

  ensureDir(config.schemaDir);

  await withClient(config.connectionString, async (client) => {
    const tables = await getExistingTables(client, config.pgSchema);
    logger.info(`Found ${tables.length} tables in schema "${config.pgSchema}"`);

    // Filter out the schema-flow history table
    const userTables = tables.filter(
      (t) => t !== config.historyTable.replace(/^_/, "").replace(/_/g, "_") && t !== config.historyTable,
    );

    for (const tableName of userTables) {
      const schema = await introspectTable(client, tableName, config.pgSchema);
      const yamlContent = tableSchemaToYaml(schema);
      const filePath = path.join(config.schemaDir, `${tableName}.yaml`);

      writeFileSync(filePath, yamlContent, "utf-8");
      generatedFiles.push(filePath);
      logger.success(`Generated: ${filePath}`);
    }

    // Generate function schemas
    const functions = await getExistingFunctions(client, config.pgSchema);
    if (functions.length > 0) {
      logger.info(`Found ${functions.length} functions`);
      for (const fn of functions) {
        const yamlContent = functionToYaml(fn);
        const filePath = path.join(config.schemaDir, `fn_${fn.routine_name}.yaml`);

        writeFileSync(filePath, yamlContent, "utf-8");
        generatedFiles.push(filePath);
        logger.success(`Generated: ${filePath}`);
      }
    }
  });

  logger.success(`Generated ${generatedFiles.length} schema files`);
  return generatedFiles;
}

/** Convert a TableSchema to clean YAML */
function tableSchemaToYaml(schema: TableSchema): string {
  // Build a clean object for YAML output
  const obj: Record<string, unknown> = {
    table: schema.table,
    columns: schema.columns.map((col) => {
      const colObj: Record<string, unknown> = {
        name: col.name,
        type: col.type,
      };

      if (col.primary_key) colObj.primary_key = true;
      if (col.nullable === true) colObj.nullable = true;
      if (col.unique) colObj.unique = true;
      if (col.default !== undefined) colObj.default = col.default;
      if (col.references) {
        colObj.references = {
          table: col.references.table,
          column: col.references.column,
        };
        if (col.references.on_delete && col.references.on_delete !== "NO ACTION") {
          (colObj.references as Record<string, string>).on_delete = col.references.on_delete;
        }
        if (col.references.on_update && col.references.on_update !== "NO ACTION") {
          (colObj.references as Record<string, string>).on_update = col.references.on_update;
        }
      }

      return colObj;
    }),
  };

  if (schema.primary_key && schema.primary_key.length > 0) {
    obj.primary_key = schema.primary_key;
  }

  if (schema.indexes && schema.indexes.length > 0) {
    obj.indexes = schema.indexes;
  }

  if (schema.checks && schema.checks.length > 0) {
    obj.checks = schema.checks;
  }

  return `# Schema for table: ${schema.table}\n# Generated by schema-flow\n\n${toYaml(obj, { lineWidth: 120 })}\n`;
}

/** Convert a DB function to YAML */
function functionToYaml(fn: {
  routine_name: string;
  external_language: string;
  data_type: string;
  routine_definition: string;
  parameter_list: string;
}): string {
  const obj = {
    name: fn.routine_name,
    language: fn.external_language?.toLowerCase() || "plpgsql",
    returns: fn.data_type || "void",
    args: fn.parameter_list || "",
    body: fn.routine_definition || "",
    replace: true,
  };

  return `# Function: ${fn.routine_name}\n# Generated by schema-flow\n\n${toYaml(obj, { lineWidth: 120 })}\n`;
}

/** Scaffold the conventional directory structure */
export function scaffoldInit(baseDir: string): void {
  const sfDir = path.join(baseDir, "schema-flow");
  const dirs = ["schema", "pre", "post"];
  for (const dir of dirs) {
    const fullPath = path.join(sfDir, dir);
    ensureDir(fullPath);
    logger.success(`Created directory: ${fullPath}`);
  }

  // Create .gitkeep files so empty dirs are tracked
  for (const dir of dirs) {
    const gitkeepPath = path.join(sfDir, dir, ".gitkeep");
    if (!existsSync(gitkeepPath)) {
      writeFileSync(gitkeepPath, "", "utf-8");
    }
  }

  logger.success("Initialized schema-flow directory structure");
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase();
}

function ensureDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}
