// src/scaffold/index.ts
// Scaffolding helpers: generate pre/post scripts, generate YAML from existing DB

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import { stringify as toYaml } from "yaml";
import type { SchemaFlowConfig } from "../core/config.js";
import type { TableSchema } from "../schema/types.js";
import { getExistingTables, introspectTable, getExistingFunctions, getExistingEnums, getExistingExtensions, getExistingViews, getExistingMaterializedViews, getTableComment, getColumnComments, getEnumComment, getViewComment, getMaterializedViewComment, getFunctionComment, getIndexComments, getTriggerComments, getPolicyComments } from "../introspect/index.js";
import { withClient } from "../core/db.js";
import { logger } from "../core/logger.js";
import { utcTimestamp } from "../core/files.js";

/** Scaffold a pre-migration SQL script */
export function scaffoldPre(config: SchemaFlowConfig, name: string): string {
  const ts = utcTimestamp();
  const filename = `${ts}_${sanitizeName(name)}.sql`;
  const filePath = path.join(config.preDir, filename);

  ensureDir(config.preDir);

  const content = `-- Pre-migration script: ${name}
-- Generated by schema-flow at ${new Date().toISOString()}
-- This script runs BEFORE declarative schema migration.
-- Use for: column renames, data transformations, backfills, etc.

-- Example: rename a column
-- ALTER TABLE "public"."users" RENAME COLUMN "name" TO "full_name";

BEGIN;

-- Your SQL here

COMMIT;
`;

  writeFileSync(filePath, content, "utf-8");
  logger.success(`Created pre-migration script: ${filePath}`);
  return filePath;
}

/** Scaffold a post-migration SQL script */
export function scaffoldPost(config: SchemaFlowConfig, name: string): string {
  const ts = utcTimestamp();
  const filename = `${ts}_${sanitizeName(name)}.sql`;
  const filePath = path.join(config.postDir, filename);

  ensureDir(config.postDir);

  const content = `-- Post-migration script: ${name}
-- Generated by schema-flow at ${new Date().toISOString()}
-- This script runs AFTER declarative schema migration.
-- Use for: seed data, grants, materialized view refreshes, etc.

BEGIN;

-- Your SQL here

COMMIT;
`;

  writeFileSync(filePath, content, "utf-8");
  logger.success(`Created post-migration script: ${filePath}`);
  return filePath;
}

/** Generate YAML schema files from an existing database */
export async function generateFromDb(config: SchemaFlowConfig): Promise<string[]> {
  logger.banner("Generating schema files from existing database");
  const generatedFiles: string[] = [];

  ensureDir(config.schemaDir);
  ensureDir(config.preDir);
  ensureDir(config.postDir);
  ensureDir(config.mixinsDir);
  ensureDir(config.repeatableDir);

  await withClient(config.connectionString, async (client) => {
    // Generate extensions
    const extensions = await getExistingExtensions(client);
    if (extensions.length > 0) {
      const yamlContent = `# Extensions managed by schema-flow\n# Generated by schema-flow\n\n${toYaml({ extensions }, { lineWidth: 120 })}\n`;
      const filePath = path.join(config.schemaDir, "extensions.yaml");
      writeFileSync(filePath, yamlContent, "utf-8");
      generatedFiles.push(filePath);
      logger.success(`Generated: ${filePath}`);
    }

    // Generate enums
    const enums = await getExistingEnums(client, config.pgSchema);
    if (enums.length > 0) {
      logger.info(`Found ${enums.length} enum(s)`);
      for (const e of enums) {
        const enumObj: Record<string, unknown> = { enum: e.name, values: e.values };
        const enumComment = await getEnumComment(client, e.name, config.pgSchema);
        if (enumComment) enumObj.comment = enumComment;
        const yamlContent = `# Enum: ${e.name}\n# Generated by schema-flow\n\n${toYaml(enumObj, { lineWidth: 120 })}\n`;
        const filePath = path.join(config.schemaDir, `enum_${e.name}.yaml`);
        writeFileSync(filePath, yamlContent, "utf-8");
        generatedFiles.push(filePath);
        logger.success(`Generated: ${filePath}`);
      }
    }

    const tables = await getExistingTables(client, config.pgSchema);
    logger.info(`Found ${tables.length} tables in schema "${config.pgSchema}"`);

    // Filter out the schema-flow history table
    const userTables = tables.filter(
      (t) => t !== config.historyTable.replace(/^_/, "").replace(/_/g, "_") && t !== config.historyTable,
    );

    for (const tableName of userTables) {
      const schema = await introspectTable(client, tableName, config.pgSchema);

      // Add comments
      const tableComment = await getTableComment(client, tableName, config.pgSchema);
      if (tableComment) schema.comment = tableComment;
      const colComments = await getColumnComments(client, tableName, config.pgSchema);
      for (const col of schema.columns) {
        const comment = colComments.get(col.name);
        if (comment) col.comment = comment;
      }
      const idxComments = await getIndexComments(client, tableName, config.pgSchema);
      if (schema.indexes) {
        for (const idx of schema.indexes) {
          const idxName = idx.name || `idx_${tableName}_${idx.columns.join("_")}`;
          const comment = idxComments.get(idxName);
          if (comment) idx.comment = comment;
        }
      }
      const trigComments = await getTriggerComments(client, tableName, config.pgSchema);
      if (schema.triggers) {
        for (const trigger of schema.triggers) {
          const comment = trigComments.get(trigger.name);
          if (comment) trigger.comment = comment;
        }
      }
      const polComments = await getPolicyComments(client, tableName, config.pgSchema);
      if (schema.policies) {
        for (const policy of schema.policies) {
          const comment = polComments.get(policy.name);
          if (comment) policy.comment = comment;
        }
      }

      const yamlContent = tableSchemaToYaml(schema);
      const filePath = path.join(config.schemaDir, `${tableName}.yaml`);

      writeFileSync(filePath, yamlContent, "utf-8");
      generatedFiles.push(filePath);
      logger.success(`Generated: ${filePath}`);
    }

    // Generate function schemas
    const functions = await getExistingFunctions(client, config.pgSchema);
    if (functions.length > 0) {
      logger.info(`Found ${functions.length} functions`);
      for (const fn of functions) {
        const fnComment = await getFunctionComment(client, fn.routine_name, config.pgSchema);
        const yamlContent = functionToYaml(fn, fnComment);
        const filePath = path.join(config.schemaDir, `fn_${fn.routine_name}.yaml`);

        writeFileSync(filePath, yamlContent, "utf-8");
        generatedFiles.push(filePath);
        logger.success(`Generated: ${filePath}`);
      }
    }

    // Generate views
    const views = await getExistingViews(client, config.pgSchema);
    if (views.length > 0) {
      logger.info(`Found ${views.length} view(s)`);
      for (const v of views) {
        const viewObj: Record<string, unknown> = { view: v.name, query: v.query };
        const viewComment = await getViewComment(client, v.name, config.pgSchema);
        if (viewComment) viewObj.comment = viewComment;
        const yamlContent = `# View: ${v.name}\n# Generated by schema-flow\n\n${toYaml(viewObj, { lineWidth: 120 })}\n`;
        const filePath = path.join(config.schemaDir, `view_${v.name}.yaml`);
        writeFileSync(filePath, yamlContent, "utf-8");
        generatedFiles.push(filePath);
        logger.success(`Generated: ${filePath}`);
      }
    }

    // Generate materialized views
    const mvs = await getExistingMaterializedViews(client, config.pgSchema);
    if (mvs.length > 0) {
      logger.info(`Found ${mvs.length} materialized view(s)`);
      for (const mv of mvs) {
        const obj: Record<string, unknown> = { materialized_view: mv.name, query: mv.query };
        if (mv.indexes && mv.indexes.length > 0) obj.indexes = mv.indexes;
        const mvComment = await getMaterializedViewComment(client, mv.name, config.pgSchema);
        if (mvComment) obj.comment = mvComment;
        const yamlContent = `# Materialized View: ${mv.name}\n# Generated by schema-flow\n\n${toYaml(obj, { lineWidth: 120 })}\n`;
        const filePath = path.join(config.schemaDir, `mv_${mv.name}.yaml`);
        writeFileSync(filePath, yamlContent, "utf-8");
        generatedFiles.push(filePath);
        logger.success(`Generated: ${filePath}`);
      }
    }
  });

  logger.success(`Generated ${generatedFiles.length} schema files`);
  return generatedFiles;
}

/** Convert a TableSchema to clean YAML */
function tableSchemaToYaml(schema: TableSchema): string {
  // Build a clean object for YAML output
  const obj: Record<string, unknown> = {
    table: schema.table,
  };

  if (schema.comment) {
    obj.comment = schema.comment;
  }

  obj.columns = schema.columns.map((col) => {
      const colObj: Record<string, unknown> = {
        name: col.name,
        type: col.type,
      };

      if (col.primary_key) colObj.primary_key = true;
      if (col.nullable === true) colObj.nullable = true;
      if (col.unique) colObj.unique = true;
      if (col.default !== undefined) colObj.default = col.default;
      if (col.generated) colObj.generated = col.generated;
      if (col.comment) colObj.comment = col.comment;
      if (col.references) {
        colObj.references = {
          table: col.references.table,
          column: col.references.column,
        };
        if (col.references.on_delete && col.references.on_delete !== "NO ACTION") {
          (colObj.references as Record<string, string>).on_delete = col.references.on_delete;
        }
        if (col.references.on_update && col.references.on_update !== "NO ACTION") {
          (colObj.references as Record<string, string>).on_update = col.references.on_update;
        }
      }

      return colObj;
    });

  if (schema.primary_key && schema.primary_key.length > 0) {
    obj.primary_key = schema.primary_key;
  }

  if (schema.indexes && schema.indexes.length > 0) {
    obj.indexes = schema.indexes;
  }

  if (schema.checks && schema.checks.length > 0) {
    obj.checks = schema.checks;
  }

  if (schema.triggers && schema.triggers.length > 0) {
    obj.triggers = schema.triggers.map((t) => {
      const trigObj: Record<string, unknown> = {
        name: t.name,
        timing: t.timing,
        events: t.events,
        function: t.function,
        for_each: t.for_each,
      };
      if (t.when) trigObj.when = t.when;
      if (t.comment) trigObj.comment = t.comment;
      return trigObj;
    });
  }

  if (schema.rls) {
    obj.rls = true;
  }

  if (schema.force_rls) {
    obj.force_rls = true;
  }

  if (schema.policies && schema.policies.length > 0) {
    obj.policies = schema.policies.map((p) => {
      const polObj: Record<string, unknown> = {
        name: p.name,
        for: p.for,
      };
      if (p.to && p.to.length > 0) polObj.to = p.to;
      if (p.using) polObj.using = p.using;
      if (p.check) polObj.check = p.check;
      if (p.permissive === false) polObj.permissive = false;
      if (p.comment) polObj.comment = p.comment;
      return polObj;
    });
  }

  return `# Schema for table: ${schema.table}\n# Generated by schema-flow\n\n${toYaml(obj, { lineWidth: 120 })}\n`;
}

/** Convert a DB function to YAML */
function functionToYaml(fn: {
  routine_name: string;
  external_language: string;
  data_type: string;
  routine_definition: string;
  parameter_list: string;
  security_type?: string;
}, comment?: string | null): string {
  const obj: Record<string, unknown> = {
    name: fn.routine_name,
    language: fn.external_language?.toLowerCase() || "plpgsql",
    returns: fn.data_type || "void",
    args: fn.parameter_list || "",
    body: fn.routine_definition || "",
    replace: true,
  };

  if (fn.security_type === "DEFINER") {
    obj.security = "definer";
  }

  if (comment) {
    obj.comment = comment;
  }

  return `# Function: ${fn.routine_name}\n# Generated by schema-flow\n\n${toYaml(obj, { lineWidth: 120 })}\n`;
}

/** Scaffold the conventional directory structure */
export function scaffoldInit(baseDir: string): void {
  const sfDir = path.join(baseDir, "schema-flow");
  const dirs = ["schema", "pre", "post", "mixins", "repeatable"];
  for (const dir of dirs) {
    const fullPath = path.join(sfDir, dir);
    ensureDir(fullPath);
    logger.success(`Created directory: ${fullPath}`);
  }

  // Create .gitkeep files so empty dirs are tracked
  for (const dir of dirs) {
    const gitkeepPath = path.join(sfDir, dir, ".gitkeep");
    if (!existsSync(gitkeepPath)) {
      writeFileSync(gitkeepPath, "", "utf-8");
    }
  }

  logger.success("Initialized schema-flow directory structure");
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase();
}

function ensureDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}
