-- Pre-migration script: rename_name_to_display_name
-- Generated by schema-flow at 2026-02-28T00:00:00.000Z
-- This script runs BEFORE declarative schema migration.

-- Rename the "name" column to "display_name" on the users table.
-- Column renames can't be expressed declaratively, so use a pre-migration script.

BEGIN;

ALTER TABLE "public"."users" RENAME COLUMN "name" TO "display_name";

COMMIT;
