-- Post-migration script: seed_default_tags
-- Generated by schema-flow at 2026-02-28T00:00:00.000Z
-- This script runs AFTER declarative schema migration.

BEGIN;

INSERT INTO "public"."tags" (name) VALUES
  ('general'),
  ('announcement'),
  ('tutorial')
ON CONFLICT (name) DO NOTHING;

COMMIT;
